name: digify_hr_system
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  # Core & Localization
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^14.6.2

  # Networking
  dio: ^5.4.0

  # UI & Styling
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.3
  google_fonts: ^6.2.1
  reorderables: ^0.6.0

  # Utilities
  intl: any
  skeletonizer: ^2.1.2
  flutter_colorpicker: ^1.1.0
  pull_down_button: ^0.10.2
  dropdown_button2: ^2.3.9
  gap: ^3.0.1

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0

  # Linting
  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/gen/
  line_length: 120
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      class_name: Assets

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/icons/workforce/
    - assets/icons/sidebar/
    - assets/icons/time_management/
